### ISSUE TITLE
coverage --summary generates negative sequencing-coverage values

### ISSUE THREAD

**Issue by QLamyBesnier** [arumugamlab/msamtools#9]
Hello,

Thanks for this great tool.

While running msamtools coverage --summary on a filtered bam file, I sometimes come accross negative values in the 3rd column of the generated output (sequencing-coverage values).

Any idea of what is causing it? I've been using msamtools for many samples and thousands of genomes without problem but this seems to happen sometimes for highly covered genomes from what I've seen sor far (maybe some sort of overflow?).

Here is my basic workflow:

1. Alignment (paired-end reads) with BWA-mem2
2. Sam -> Bam -> sort -n with samtools
3. msamtools filter (with your recommended values)
4. msamtools coverage --summary -o output.txt.gz input_filtered.bam

I can send you example bam files for which I encouter this issue, just tell me to which email address.

**Comment by microbiomix** [comment]
Hi, 
Can you please check which version of `msamtools` you are using? We identified this problem and fixed in in January 2023, so it should not be doing this since `v1.1.2`. It was indeed due to `int32_t` overflow in number of bases covering a sequence. But it is now `int64_t` and should handle up to petabases per sequence. If it is the latest version of `msamtools`, then there is likely another bug that I should look into.

**Comment by QLamyBesnier** [comment]
Thank you for the quick answer.

Indeed, I am still using version 1.0.0, I should have looked for updates, my apologies.

I will get the latest version, test it, and let you know if I still encounter this problem.

**Comment by microbiomix** [comment]
There have been a few new features since `v1.0.0`, perhaps some of them are useful to you. Plus, you can get it from `bioconda`.

If you switch to `v1.1.0+` the output from `msamtools profile --multi=prop` will be different from `v1.0.0`. Please see release notes for `v1.1.0`. If you have old profiles, you may want to port them to the new version for future comparability.

I will close this for now. Please do let me know if you run into any issues by reopening this.

**Comment by QLamyBesnier** [comment]
Perfect! Thanks for the heads up.
